### ISSUE TITLE
Issues while generating availability report.

### ISSUE THREAD

**Issue by Kumar888** [statusengine/worker#20]
Hi,

We have created Availability report generation python script, we are facing some percentage differences for perticuler period of days example 10 days duration than generating report each day and caluculating percentage manually for 10 days.

Issue: example scenario: if create a report for each day getting 100 % and for 10 days it should be 100 % available, but while creating report for period of 10 days it's 98.50.

i'm getting differences(eg: -1,-2,-3 etc) in report while generating for perticuler period than generating and caluculating on daily basis.

Can you please suggest a way to solve this issue as it serious issue as per percentage differences.

Thanks
Vijay

**Comment by nook24** [comment]
Please see my last post in https://github.com/statusengine/worker/issues/16#issuecomment-502147533

**Comment by Kumar888** [comment]
Closing this issue as my script has some issue.
