### ISSUE TITLE
Elastic Authentication?

### ISSUE THREAD

**Issue by steaksauce-** [statusengine/worker#21]
Elastic recently made security available with their basic license (https://www.elastic.co/blog/security-for-elasticsearch-is-now-free). As such, I decided to _attempt_ an Elastic backend with security enabled on Elastic. However, I get a non-fatal error when restarting the worker:
```
statusengine-worker[17621]: No alive nodes found in your cluster
statusengine-worker[17621]: Elasticsearch error!
```
I did some basic troubleshooting on the Elastic server and found that I now have to authenticate to Elastic (I feel stupid for not realizing this sooner).

So my problem is this: is there a way to configure Elastic authentication on the `statusengine-worker`? I don't see anything in the documentation. I pilfered through #1 and didn't see any mention of it there either.

**Comment by nook24** [comment]
Have you already tried to pass it as the [elastic docs](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/security.html) describes?

Can you please try if passing the host as
```YML
elasticsearch_address: http://username@password@10.10.10.10
```
in your [config.yml](https://github.com/statusengine/worker/blob/02267d495ae69137d6765dc6b0f453f80216f1cf/etc/config.yml.example#L220) works?

Also make sure to follow the ES6 guide and install elasticsearch 6.x php drivers.
https://statusengine.org/tutorials/Elasticsearch6-Perfdata-Backend/

**Comment by steaksauce-** [comment]
I will give those a try, but in doing so I found that my elastic instance was listening on localhost, and not bound to the IP. I'm having the hardest time getting elastic to listen on anything but localhost and will update when I figure this out.

**Comment by steaksauce-** [comment]
Seems like a combination of selinux and a misconfiguration on the elastic node caused my troubles.

Using the defined method of `elasticsearch_address: http://username:password@10.10.10.10` works. Thanks!
