### ISSUE TITLE
Use a external command 

### ISSUE THREAD

**Issue by duylong** [statusengine/worker#27]
Hi,

I can't use external_command_file, my statusengine worker is not on the same naemon machine. I would like to use an external command, for example in using Thruk API Rest (https://www.thruk.org/documentation/rest_commands.html). 

What do you think?

**Comment by nook24** [comment]
The new [Statusengine Broker](https://github.com/statusengine/broker) also supports processing of external commands through a dedicated Gearman queue.
Unfortunately it's not yet implemented in the worker 😅

We are working on a new release but there is still a lot of work to be done first.

**Comment by nook24** [comment]
Version 3.7 is released. Please see the changelog for update instructions: https://github.com/statusengine/worker/releases/tag/3.7.0
